version: 2.1

orbs:
    tailscale: hubci/tailscale@0.3.1

jobs:
    deploy:
        docker:
            - image: cimg/base:2022.09
              auth:
                  username: $DOCKER_USERNAME
                  password: $DOCKER_PASSWORD
        parameters:
            auth-key:
                type: env_var_name
                default: TS_AUTHKEY

        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: Build Docker image
                  command: |
                      docker build -t $DOCKER_USERNAME/hello-express-test .
            - run:
                  name: Push application Docker image
                  command: |
                      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                      docker push $DOCKER_USERNAME/hello-express-test
            - tailscale/install
            - tailscale/connect
            - run:
                  command: tailscale --socket=/tmp/tailscaled.sock ping 100.110.248.12
                  name: Ping an example Tailscale machine
            - run:
                  name: Check Tailscale Status
                  command: tailscale status
            - add_ssh_keys:
                  fingerprints:
                      - SHA256:kGySpgc3I6XxXGe02JXR+Yl862rm+FtVGBAc5rfDQz0

            - run:
                  name: Deploy via SSH
                  command: |
                      ssh thanhdo@100.110.248.12

workflows:
    deploy-dev:
        jobs:
            - deploy:
                  context: dev
                  filters:
                      branches:
                          only:
                              - dev
    deploy-staging:
        jobs:
            - deploy:
                  context: staging
                  filters:
                      branches:
                          only:
                              - staging
    deploy-prod:
        jobs:
            - deploy:
                  context: prod
                  filters:
                      branches:
                          only:
                              - main
