version: 2.1

orbs:
    circleci-tailscale: threecomma/circleci-tailscale@2.2.0

jobs:
    deploy:
        docker:
            - image: cimg/base:2022.09
              auth:
                  username: $DOCKER_USERNAME
                  password: $DOCKER_PASSWORD
        parameters:
            tailscale-auth-key:
                type: env_var_name
                default: TAILSCALE_AUTH_KEY
            tailscale-proxy-address:
                type: string
                default: localhost
        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: Build Docker image
                  command: |
                      docker build -t $DOCKER_USERNAME/hello-express-test .
            - run:
                  name: Push application Docker image
                  command: |
                      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                      docker push $DOCKER_USERNAME/hello-express-test
            - add_ssh_keys:
                  fingerprints:
                      - SHA256:kGySpgc3I6XxXGe02JXR+Yl862rm+FtVGBAc5rfDQz0
            - circleci-tailscale/connect
            - run:
                  name: curl a tailscale machine over port 8080
                  command: |
                      curl "http://thanhdo.tail83e1de.ts.net"
                      ssh thanhdo@100.110.248.12

workflows:
    deploy-dev:
        jobs:
            - deploy:
                  context: dev
                  filters:
                      branches:
                          only:
                              - dev
    deploy-staging:
        jobs:
            - deploy:
                  context: staging
                  filters:
                      branches:
                          only:
                              - staging
    deploy-prod:
        jobs:
            - deploy:
                  context: prod
                  filters:
                      branches:
                          only:
                              - main
