version: 2.1

orbs:
    circleci-tailscale: threecomma/circleci-tailscale@2.2.0

jobs:
    deploy:
        docker:
            - image: cimg/base:2022.09
              auth:
                  username: $DOCKER_USERNAME
                  password: $DOCKER_PASSWORD
        parameters:
            tailscale-auth-key:
                type: env_var_name
                default: TAILSCALE_AUTH_KEY
            tailscale-proxy-address:
                type: string
                default: localhost
        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: Check environment
                  command: |
                      echo "Deploying to $ENVIRONMENT environment"
            - run:
                  name: Build Docker image
                  command: |
                      docker build -t $DOCKER_NAMESPACE/hello-express_$ENVIRONMENT .
            - run:
                  name: Push application Docker image
                  command: |
                      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                      docker push $DOCKER_NAMESPACE/hello-express_$ENVIRONMENT
            - circleci-tailscale/connect
            - run:
                  name: curl a tailscale machine over port 8080
                  command: |
                      curl "http://$SERVER_HOST"
            - run:
                  name: Deploy Over SSH
                  command: |
                      ssh $SERVER_USERNAME@$SERVER_HOST \<< EOF
                          ls
                          cd /app/hello-express
                          git checkout dev
                          git pull
                      EOF

workflows:
    deploy-dev:
        jobs:
            - deploy:
                  context: dev
                  filters:
                      branches:
                          only:
                              - dev
    deploy-staging:
        jobs:
            - deploy:
                  context: staging
                  filters:
                      branches:
                          only:
                              - staging
    deploy-prod:
        jobs:
            - deploy:
                  context: prod
                  filters:
                      branches:
                          only:
                              - main
