version: 2.1

orbs:
    ts: hubci/tailscale@0.1
jobs:
    deploy:
        docker:
            - image: cimg/node:23.1.0
              auth:
                  username: $DOCKER_USERNAME
                  password: $DOCKER_PASSWORD
        parameters:
            auth-key:
                type: env_var_name
                default: TS_AUTHKEY
           
        steps:      
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: Build Docker image
                  command: |
                      docker build -t $DOCKER_USERNAME/hello-express-test .
            - run:
                  name: Push application Docker image
                  command: |
                      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                      docker push $DOCKER_USERNAME/hello-express-test
            - ts/install
            - ts/connect
            - run:
                  name: Ping to server
                  command: |
                      curl "http://100.110.248.12"    
            - run:
                name: ssh to server
                command: |
                      ssh thanhdo@100.110.248.12             
workflows:
    deploy-dev:
        jobs:
            - deploy:
                  context: dev
                  filters:
                      branches:
                          only:
                              - dev
    deploy-staging:
        jobs:
            - deploy:
                  context: staging
                  filters:
                      branches:
                          only:
                              - staging
    deploy-prod:
        jobs:
            - deploy:
                  context: prod
                  filters:
                      branches:
                          only:
                              - main
