version: 2.1

orbs:
  docker: circleci/docker@2.8.1

jobs:
    build:
        docker:
            - image: cimg/base:stable # the primary container, where your job's commands are run
        steps:
            - checkout # check out the code in the project directory
            - docker/check:
                arch: amd64 
                use-docker-credentials-store: false 
                docker-password: DOCKER_PASSWORD 
                docker-username: DOCKER_USERNAME
            - docker/build:
                docker-context: . 
                path: . 
                image: thanhmati/hello-express-test 
             

workflows:
    deploy-workflow:
        jobs:
            - build
            - docker/publish:
                image: thanhmati/hello-express-test
