name: Dev CI/CD Workflow

on:
    push:
        branches: ["dev"]
    pull_request:
        branches: ["dev"]

jobs:
    call-reusableWorkflow:
        name: run the job
        uses: ./.github/workflows/reusableWorkflow.yml
        with:
            stage: "dev"
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
