name: Prod CI/CD Workflow

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    call-reusableWorkflow:
        name: run the job
        uses: ./.github/workflows/reusableWorkflow.yml
        with:
            stage: "prod"
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}
            TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
            SERVER_HOST: ${{ secrets.SERVER_HOST }}
            SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
            SERVER_KEY: ${{ secrets.SERVER_KEY }}
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
