name: Staging CI/CD Workflow

on:
    push:
        branches: ["staging"]
    pull_request:
        branches: ["staging"]

jobs:
    call-reusableWorkflow:
        name: run the job
        uses: ./.github/workflows/reusableWorkflow.yml
        with:
            environment: "staging"
        secrets:
            SERVER_HOST: ${{ secrets.STAGING_SERVER_HOST }}
            SERVER_USERNAME: ${{ secrets.STAGING_SERVER_USERNAME }}
