name: Reusable CI Workflow

on:
    workflow_call:
        inputs:
            stage:
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Docker login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build the Docker image
              run: docker build -t ${{ secrets.DOCKER_NAMESPACE }}/hello-express_${{inputs.stage}}:latest .

            - name: Publish the Docker image to Docker Hub
              run: docker push ${{ secrets.DOCKER_NAMESPACE }}/hello-express_${{inputs.stage}}:latest
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Tailscale
              uses: tailscale/github-action@v2
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

            - name: SSH to server
              uses: appleboy/ssh-action@v1.1.0
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SERVER_KEY }}
                  port: ${{ secrets.SERVER_PORT }}
                  script: |
                      ls
                      cd app/hello-express
                      docker compose -f docker-compose.${{inputs.stage}}.yml pull
                      docker compose -f docker-compose.${{inputs.stage}}.yml up -d
                      docker system prune -af
